#!/bin/bash
#
# Writes the gitignored ios/ShareCore/Configuration/AppSecrets.swift.
#
# - TLINGO_CLOUD_SECRET set: write real values from TLINGO_* environment variables (CI).
# - File already exists: keep it (local developer copy).
# - Otherwise: write placeholders so the app compiles with cloud features disabled.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$ROOT/ios/ShareCore/Configuration/AppSecrets.swift"

if [[ -z "${TLINGO_CLOUD_SECRET:-}" && -f "$OUTPUT" ]]; then
    echo "AppSecrets.swift exists; keeping local copy"
    exit 0
fi

cat > "$OUTPUT" <<EOF
//
//  AppSecrets.swift
//  ShareCore
//
//  Generated by ci_scripts/generate-app-secrets.sh. Do not commit.
//

import Foundation

public enum AppSecrets {
    public static let cloudEndpoint = URL(string: "${TLINGO_CLOUD_ENDPOINT:-https://example.invalid}")!
    public static let cloudSecret = "${TLINGO_CLOUD_SECRET:-}"
    public static let cloudAPIVersion = "${TLINGO_CLOUD_API_VERSION:-2025-01-01-preview}"
    public static let supabaseURL = URL(string: "${TLINGO_SUPABASE_URL:-https://example.invalid}")!
    public static let supabaseAnonKey = "${TLINGO_SUPABASE_ANON_KEY:-}"
}
EOF

echo "Wrote $OUTPUT (cloud configured: $([[ -n "${TLINGO_CLOUD_SECRET:-}" ]] && echo yes || echo no))"
