#!/bin/bash
#
# Writes the gitignored ios/ShareCore/Configuration/AppSecrets.swift.
#
# - Xcode Cloud: require the credentials used by the selected distribution and
#   fail instead of shipping an app that points at placeholder hosts.
# - TLINGO_CLOUD_SECRET set: write real values from TLINGO_* environment variables.
# - Legacy AITRANSLATOR_*/SUPABASE_* names remain supported while the Xcode Cloud
#   workflows migrate to TLINGO_* names.
# - File already exists: keep it (local developer copy).
# - Otherwise: write placeholders so the app compiles with cloud features disabled.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$ROOT/ios/ShareCore/Configuration/AppSecrets.swift"

CLOUD_ENDPOINT="${TLINGO_CLOUD_ENDPOINT:-${AITRANSLATOR_CLOUD_ENDPOINT:-}}"
CLOUD_SECRET="${TLINGO_CLOUD_SECRET:-${AITRANSLATOR_CLOUD_SECRET:-}}"
SUPABASE_URL="${TLINGO_SUPABASE_URL:-${SUPABASE_URL:-}}"
SUPABASE_ANON_KEY="${TLINGO_SUPABASE_ANON_KEY:-${SUPABASE_ANON_KEY:-}}"

if [[ -n "${CI_XCODE_CLOUD:-}" ]]; then
    missing_variables=()
    [[ -n "$CLOUD_ENDPOINT" ]] || missing_variables+=("TLINGO_CLOUD_ENDPOINT")
    [[ -n "$CLOUD_SECRET" ]] || missing_variables+=("TLINGO_CLOUD_SECRET")

    if [[ "${CI_WORKFLOW:-}" == "${DIRECT_RELEASE_WORKFLOW_NAME:-Direct Release}" ]]; then
        [[ -n "$SUPABASE_URL" ]] || missing_variables+=("TLINGO_SUPABASE_URL")
        [[ -n "$SUPABASE_ANON_KEY" ]] || missing_variables+=("TLINGO_SUPABASE_ANON_KEY")
    fi

    if (( ${#missing_variables[@]} > 0 )); then
        printf 'Missing required Xcode Cloud environment variables: %s\n' \
            "${missing_variables[*]}" >&2
        echo "Configure them in the Xcode Cloud workflow before archiving TLingo." >&2
        exit 1
    fi
fi

if [[ -z "$CLOUD_SECRET" && -f "$OUTPUT" ]]; then
    echo "AppSecrets.swift exists; keeping local copy"
    exit 0
fi

cat > "$OUTPUT" <<EOF
//
//  AppSecrets.swift
//  ShareCore
//
//  Generated by ci_scripts/generate-app-secrets.sh. Do not commit.
//

import Foundation

public enum AppSecrets {
    public static let cloudEndpoint = URL(string: "${CLOUD_ENDPOINT:-https://example.invalid}")!
    public static let cloudSecret = "$CLOUD_SECRET"
    public static let cloudAPIVersion = "${TLINGO_CLOUD_API_VERSION:-2025-01-01-preview}"
    public static let supabaseURL = URL(string: "${SUPABASE_URL:-https://example.invalid}")!
    public static let supabaseAnonKey = "$SUPABASE_ANON_KEY"
}
EOF

echo "Wrote $OUTPUT (cloud configured: $([[ -n "$CLOUD_SECRET" ]] && echo yes || echo no), Supabase configured: $([[ -n "$SUPABASE_ANON_KEY" ]] && echo yes || echo no))"
