//
//  ConfigurationMigrator.swift
//  ShareCore
//

import Foundation
import os

private let logger = os.Logger(subsystem: "com.zanderwang.AITranslator", category: "Migrator")

/// Migrates persisted `AppConfiguration` from older versions to the current version.
///
/// Each migration step transforms the configuration one minor version at a time
/// (e.g. 1.1.0 -> 1.2.0). Steps are applied sequentially so that any saved
/// configuration — regardless of how old — can reach `AppConfiguration.currentVersion`.
public enum ConfigurationMigrator {
    /// Migrate `config` to `AppConfiguration.currentVersion`.
    /// Returns the migrated configuration and a flag indicating whether any
    /// migration was actually performed.
    public static func migrateIfNeeded(
        _ config: AppConfiguration
    ) -> (config: AppConfiguration, didMigrate: Bool) {
        var result = config
        var didMigrate = false

        // 1.1.x -> 1.2.0
        if versionCompare(result.version, isLessThan: "1.2.0") {
            result = migrate_1_1_to_1_2(result)
            didMigrate = true
        }

        // 1.2.x -> 1.3.0
        if versionCompare(result.version, isLessThan: "1.3.0") {
            result = migrate_1_2_to_1_3(result)
            didMigrate = true
        }

        // 1.3.x -> 1.4.0
        if versionCompare(result.version, isLessThan: "1.4.0") {
            result = migrate_1_3_to_1_4(result)
            didMigrate = true
        }

        // 1.4.x -> 1.5.0
        if versionCompare(result.version, isLessThan: "1.5.0") {
            result = migrate_1_4_to_1_5(result)
            didMigrate = true
        }

        // 1.5.x -> 1.6.0
        if versionCompare(result.version, isLessThan: "1.6.0") {
            result = migrate_1_5_to_1_6(result)
            didMigrate = true
        }

        return (result, didMigrate)
    }

    private static let sentenceTranslateName = NSLocalizedString(
        "Sentence Translate",
        comment: "Name of the sentence-by-sentence translation action"
    )

    private static let sentenceTranslatePrompt =
        [
            "Translate the text below sentence by sentence from {{sourceLanguage}} to {{targetLanguage}}.",
            "",
            "Text:",
            "{{text}}",
            "",
            "Rules:",
            "- Split the input into sentences while keeping punctuation with each sentence.",
            "- Preserve the original meaning, tone, and style.",
            "- Use natural, fluent {{targetLanguage}} for each translation.",
            "- Return original-translation pairs only.",
        ].joined(separator: "\n")

    private static let previousSentenceTranslatePrompt =
        "If input is in {{targetLanguage}}, translate sentence by sentence to English; " +
        "otherwise translate to {{targetLanguage}}. Return original-translation pairs. Keep meaning and style."

    // MARK: - 1.1.x -> 1.2.0

    /// Migration: replace old-format translate prompts with the new
    /// `{text}` / `{sourceLanguage}` / `{targetLanguage}` template.
    private static func migrate_1_1_to_1_2(
        _ config: AppConfiguration
    ) -> AppConfiguration {
        let translateName = NSLocalizedString(
            "Translate",
            comment: "Name of the translate action"
        )

        let newTranslatePrompt = BuiltInActionCatalog.prompt(named: "Translate") ?? ""

        var migrated = config
        migrated.version = "1.2.0"

        migrated.actions = migrated.actions.map { entry in
            guard entry.name == translateName else { return entry }

            // Only replace if the prompt matches a known old format.
            // User-customized prompts are left untouched.
            if isOldTranslatePrompt(entry.prompt) {
                var updated = entry
                updated.prompt = newTranslatePrompt
                logger.debug("Migrated translate prompt for action '\(entry.name, privacy: .public)'")
                return updated
            }

            return entry
        }

        logger.info("Migration 1.1 -> 1.2 complete")
        return migrated
    }

    /// Recognizes old translate prompt formats that should be migrated.
    ///
    /// Known old patterns:
    /// - `"If input is in <lang>, translate to <lang>; otherwise translate to <lang>. …"`
    ///   (the format generated by the pre-refactor `ManagedActionTemplate`)
    static func isOldTranslatePrompt(_ prompt: String) -> Bool {
        prompt.hasPrefix("If input is in ")
    }

    // MARK: - 1.2.x -> 1.3.0

    /// Migration: remove `{fallbackLanguage}` / `{{fallbackLanguage}}` from prompts.
    ///
    /// Actions affected: Sentence Translate, Grammar Check, Sentence Analysis.
    /// Only prompts that still contain `fallbackLanguage` are replaced.
    private static func migrate_1_2_to_1_3(
        _ config: AppConfiguration
    ) -> AppConfiguration {
        var migrated = config
        migrated.version = "1.3.0"

        migrated.actions = migrated.actions.map { entry in
            guard containsFallbackLanguage(entry.prompt) else { return entry }

            var updated = entry

            if let replacement = newPromptForAction(named: entry.name) {
                updated.prompt = replacement
                logger.debug("Migrated fallbackLanguage prompt for action '\(entry.name, privacy: .public)'")
            }

            return updated
        }

        logger.info("Migration 1.2 -> 1.3 complete")
        return migrated
    }

    /// Returns `true` if the prompt contains `{fallbackLanguage}` or `{{fallbackLanguage}}`.
    static func containsFallbackLanguage(_ prompt: String) -> Bool {
        prompt.contains("{fallbackLanguage}") || prompt.contains("{{fallbackLanguage}}")
    }

    /// Returns the replacement prompt for known action names that used `fallbackLanguage`,
    /// or `nil` for unrecognized actions.
    private static func newPromptForAction(named name: String) -> String? {
        let grammarCheckName = NSLocalizedString(
            "Grammar Check",
            comment: "Name of the grammar check action"
        )
        let sentenceAnalysisName = NSLocalizedString(
            "Sentence Analysis",
            comment: "Name of the sentence analysis action"
        )

        switch name {
        case sentenceTranslateName:
            return BuiltInActionCatalog.prompt(named: "Sentence Translate") ?? sentenceTranslatePrompt
        case grammarCheckName:
            return BuiltInActionCatalog.prompt(named: "Grammar Check")
        case sentenceAnalysisName:
            return BuiltInActionCatalog.prompt(named: "Sentence Analysis")
        default:
            return nil
        }
    }

    // MARK: - 1.3.x -> 1.4.0

    /// Migration: add `category: "translation"` to Translate and Sentence Translate actions.
    private static func migrate_1_3_to_1_4(
        _ config: AppConfiguration
    ) -> AppConfiguration {
        let translateName = NSLocalizedString(
            "Translate",
            comment: "Name of the translate action"
        )
        let sentenceTranslateName = NSLocalizedString(
            "Sentence Translate",
            comment: "Name of the sentence-by-sentence translation action"
        )

        var migrated = config
        migrated.version = "1.4.0"

        migrated.actions = migrated.actions.map { entry in
            if entry.name == translateName || entry.name == sentenceTranslateName ||
                entry.name == "Translate" || entry.name == "Sentence Translate"
            {
                var updated = entry
                updated.category = "translation"
                logger.debug("Set category=translation for action '\(entry.name, privacy: .public)'")
                return updated
            }
            return entry
        }

        logger.info("Migration 1.3 -> 1.4 complete")
        return migrated
    }

    // MARK: - 1.4.x -> 1.5.0

    /// Migration: set `outputType: "translate"` on the built-in Translate action
    /// and strip the `scenes` field (UsageScene removed).
    private static func migrate_1_4_to_1_5(
        _ config: AppConfiguration
    ) -> AppConfiguration {
        let translateName = NSLocalizedString(
            "Translate",
            comment: "Name of the translate action"
        )

        var migrated = config
        migrated.version = "1.5.0"

        migrated.actions = migrated.actions.map { entry in
            var updated = entry
            // Set outputType to "translate" for the built-in Translate action
            if entry.name == translateName || entry.name == "Translate" {
                if entry.outputType == nil || entry.outputType == "plain" {
                    updated.outputType = "translate"
                    logger.debug("Set outputType=translate for action '\(entry.name, privacy: .public)'")
                }
            }
            // Strip scenes field (UsageScene removed)
            updated.scenes = nil
            return updated
        }

        logger.info("Migration 1.4 -> 1.5 complete")
        return migrated
    }

    // MARK: - 1.5.x -> 1.6.0

    /// Migration: remove the English fallback from the built-in Sentence Translate prompt.
    private static func migrate_1_5_to_1_6(
        _ config: AppConfiguration
    ) -> AppConfiguration {
        var migrated = config
        migrated.version = "1.6.0"

        migrated.actions = migrated.actions.map { entry in
            guard entry.name == sentenceTranslateName || entry.name == "Sentence Translate",
                  entry.prompt == previousSentenceTranslatePrompt
            else {
                return entry
            }

            var updated = entry
            updated.prompt = sentenceTranslatePrompt
            logger.debug("Removed target fallback from action '\(entry.name, privacy: .public)'")
            return updated
        }

        logger.info("Migration 1.5 -> 1.6 complete")
        return migrated
    }

    // MARK: - Version comparison helpers

    /// Simple semver "less-than" check (major.minor.patch).
    static func versionCompare(
        _ lhs: String,
        isLessThan rhs: String
    ) -> Bool {
        let leftVersion = parseVersion(lhs)
        let rightVersion = parseVersion(rhs)
        if leftVersion.major != rightVersion.major { return leftVersion.major < rightVersion.major }
        if leftVersion.minor != rightVersion.minor { return leftVersion.minor < rightVersion.minor }
        return leftVersion.patch < rightVersion.patch
    }

    static func parseVersion(
        _ version: String
    ) -> (major: Int, minor: Int, patch: Int) {
        let parts = version.split(separator: ".").compactMap { Int($0) }
        return (
            major: parts.indices.contains(0) ? parts[0] : 0,
            minor: parts.indices.contains(1) ? parts[1] : 0,
            patch: parts.indices.contains(2) ? parts[2] : 0
        )
    }
}
